[versions]
agp = "9.0.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
core-ktx = "1.17.0"
ezxhelper = "3.0.1"
gson = "2.13.2"
kotlin = "2.3.0"
kotlinx-json = "1.10.0"
kotlinx-io-jvm = "0.1.16"
kotlinx-protobuf = "1.10.0"
material = "1.13.0"
materialedittext = "2.1.4"
okhttp = "5.3.2"
protobuf-java = "4.33.5"
recyclerview = "1.4.0"
xposed-api = "82"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
ezxhelper-android-utils = { module = "io.github.kyuubiran.ezxhelper:android-utils", version.ref = "ezxhelper" }
ezxhelper-core = { module = "io.github.kyuubiran.ezxhelper:core", version.ref = "ezxhelper" }
ezxhelper-xposed-api = { module = "io.github.kyuubiran.ezxhelper:xposed-api-82", version.ref = "ezxhelper" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
kotlinx-io-jvm = { module = "org.jetbrains.kotlinx:kotlinx-io-jvm", version.ref = "kotlinx-io-jvm" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-protobuf" }
materialedittext-library = { module = "com.rengwuxian.materialedittext:library", version.ref = "materialedittext" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
